### ISSUE TITLE
"Disk Identity Has Changed" -  New Docker Image Error

### ISSUE THREAD

**Issue by juan11perez** [TimJDFletcher/dockerfiles#1]
First of all thank you creating this.

I was running your initial image for about 7 days on Ubuntu 18.04 and was working very well.

Yesterday (sept 8) watctower updated the container as per your last release and now timemachine gives "disk has changed" error and wont update on the exiting backup. 

I deleted the backup and let it create a new one, but after it finished 15 minutes later was giving the same error. 

Can you please reinstate the previous image with an ubuntu tag or anything convenient.
thank you.

**Comment by anttito1** [comment]
Same here! This is apparently related to

https://lists.samba.org/archive/samba/2018-September/218145.html

https://bugzilla.samba.org/show_bug.cgi?id=13441

**Comment by juan11perez** [comment]
@anttito1 
I've since moved to this container:
https://github.com/cptactionhank/docker-netatalk
works well.

**Comment by anttito1** [comment]
Thanks! I was using netatalk before, but migrated to samba due AFP being deprecated. Had some issues with netatalk just after upgrading to Mojave.

**Comment by anttito1** [comment]
Seems that there is update to 4.9.1 coming. Need to wait Debian docker to be updated.

**Comment by anttito1** [comment]
Modified the docker file to use unstable-20181011 which has samba 2:4.9.1+dfsg-2 and created a new image. That resolved the issue.

**Comment by TimJDFletcher** [comment]
Fixed with upgrades. Sorry I didn't see the issue was here for 6 months, my bad
