### ISSUE TITLE
samba-timemachine acl errors on ZFS

### ISSUE THREAD

**Issue by BlinkyStitt** [TimJDFletcher/dockerfiles#16]
I run ubuntu 22.04 with zfsonlinux and am seeing some errors:

The first error:

```
backups-timemachine-1  | set_canon_ace_list: sys_acl_set_file on file [0D2640D0-C5E4-5D9E-809B-F96F6D873763.sparsebundle/mapped/2d99]: (Operation not supported)
```

Was easily fixed with these commands:
```
zfs set acltype=posixacl tank/backups
zfs set xattr=sa tank/backups
```

But now there's a second error:

```
backups-timemachine-1  | fruit_fset_nt_acl: SMB_VFS_NEXT_FSET_NT_ACL failed0D2640D0-C5E4-5D9E-809B-F96F6D873763.sparsebundle/mapped
backups-timemachine-1  | fruit_fset_nt_acl: SMB_VFS_NEXT_FSET_NT_ACL failed0D2640D0-C5E4-5D9E-809B-F96F6D873763.sparsebundle/bands/0
backups-timemachine-1  | fruit_fset_nt_acl: SMB_VFS_NEXT_FSET_NT_ACL failed0D2640D0-C5E4-5D9E-809B-F96F6D873763.sparsebundle/mapped/0
backups-timemachine-1  | fruit_fset_nt_acl: SMB_VFS_NEXT_FSET_NT_ACL failed0D2640D0-C5E4-5D9E-809B-F96F6D873763.sparsebundle/bands/1
backups-timemachine-1  | fruit_fset_nt_acl: SMB_VFS_NEXT_FSET_NT_ACL failed0D2640D0-C5E4-5D9E-809B-F96F6D873763.sparsebundle/mapped/1
backups-timemachine-1  | fruit_fset_nt_acl: SMB_VFS_NEXT_FSET_NT_ACL failed0D2640D0-C5E4-5D9E-809B-F96F6D873763.sparsebundle/bands/3ccc
backups-timemachine-1  | fruit_fset_nt_acl: SMB_VFS_NEXT_FSET_NT_ACL failed0D2640D0-C5E4-5D9E-809B-F96F6D873763.sparsebundle/mapped/3ccc
```

Is this a problem? I think I need to enable a `zfsacl` module, but am not sure how to do that.

https://www.samba.org/samba/docs/current/man-html/vfs_zfsacl.8.html

**Comment by WyseNynja** [comment]
trying this out: https://github.com/WyseNynja/dockerfiles/commit/6785b3820a9fbe08a99481e46f2236e3ab9e5c71

If it works, i think making this something that is part of the template will be an easy fix

**Comment by WyseNynja** [comment]
That isn't enough. The module isn't compiled.

```
backups-timemachine-1  | error probing vfs module 'zfsacl': NT_STATUS_UNSUCCESSFUL
backups-timemachine-1  | smbd_vfs_init: vfs_init_custom failed for zfsacl
backups-timemachine-1  | make_connection_snum: vfs_init failed for service IPC$
backups-timemachine-1  | Error loading module '/usr/lib/x86_64-linux-gnu/samba/vfs/zfsacl.so': /usr/lib/x86_64-linux-gnu/samba/vfs/zfsacl.so: cannot open shared object file: No such file or directory
```

**Comment by WyseNynja** [comment]
hmm. the modules that are installed are from packages. they don't include zfsacl though.

https://forums.gentoo.org/viewtopic-t-1165384.html?sid=e8b13b0025480343e6e4da4ce9e5b756

seems we have to compile from source :(

**Comment by WyseNynja** [comment]
actually, it seems it doesn't even exist yet. https://github.com/openzfs/zfs/pull/13186

So I guess the question is, how important are these ACLs?

**Comment by TimJDFletcher** [comment]
I would say that so long as the backups are working the ACL's are not important.

The design of the container is that it is only used for timemachine backups, and at least the recommended timemachine config is encrypted from the source mac meaning that access to the filesystem target is not a risk.
