### ISSUE TITLE
Doesn't start on Raspberry Pi

### ISSUE THREAD

**Issue by Vannixxo** [TimJDFletcher/dockerfiles#2]
I can't make it work on Raspberry Pi 4 with or without composer, it always tries to restart

**Comment by TimJDFletcher** [comment]
I've built and tested this on a Pi4 without issues today

**Comment by TimJDFletcher** [comment]
I've pushed a multi arch tag to dockerhub if you want to test it: 

```bash
docker pull timjdfletcher/samba-timemachine:test
docker run -t \
    -v /backups/timemachine:/backups \
    -p 10445:445 \
    --restart unless-stopped timjdfletcher/samba-timemachine
```
