### ISSUE TITLE
Time Machine not discoverable

### ISSUE THREAD

**Issue by thewinger** [TimJDFletcher/dockerfiles#5]
Hi, sorry to bother you with this but I don't really know what to do with this information

> The container only runs smbd to find it on the network the best way is avahi (mDNS) there is an example service file included. This can be copied to /etc/avahi/services/timemachine.service or run in a container.

Time Machine can't find the volume created with docker and inside the container there is no /etc/avahi/services/ folder.

What should I do to make the TM volume discoverable?

**Comment by TimJDFletcher** [comment]
You are correct, I've removed the documentation from the README. I'll readd them.

The short answer is there is an avahi service file in the git repo: https://github.com/TimJDFletcher/dockerfiles/blob/master/samba-timemachine/timemachine.service

I use this service file to allow discovery by running avahi-daemon on the docker host system.

In the case of debian install the package avahi-daemon `apt install avahi-daemon` and then copy the service file to `/etc/avahi/services/timemachine.service`

**Comment by TimJDFletcher** [comment]
I've updated the README file, if you have any feedback that would be great.

**Comment by thewinger** [comment]
Now the README it's much more clear.
I confirmed that now the disc is discoverable but it gets stuck in Connecting…

![image](https://user-images.githubusercontent.com/121455/98929656-c23ac000-24db-11eb-9fd0-cb6a253ef2e4.png)

**Comment by TimJDFletcher** [comment]
On the docker host do you get any logs from the container, using docker logs?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thewinger** [comment]
This is what logs show
```
Configuring container as a timemachine backup target
Backups will be written to: mergerfs
Creating system users
id: 'timemachine': no such user
Adding group `timemachine' (GID 998) ...
Done.
id: 'timemachine': no such user
useradd: Warning: missing or non-executable shell '/bin/nologin'
Creating SAMBA user win with a password of timemachine
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user timemachine.
Setting quote to 100000MB
Marking /backups as supported by timemmachine
Changing ownership of /backups to 1000:998, this may take a few minutes
Restricting permssions on /backups, this may take a few minutes
===================================================================================
=                 Starting SAMBA, logs after this are from SAMBA                  =
===================================================================================
smbd version 4.12.5-Debian started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
INFO: Profiling support unavailable in this build.
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
Configuring container as a timemachine backup target
Backups will be written to: mergerfs
Creating system users
Creating SAMBA user win with a password of timemachine
Setting quote to 100000MB
Marking /backups as supported by timemmachine
Changing ownership of /backups to 1000:998, this may take a few minutes
Restricting permssions on /backups, this may take a few minutes
===================================================================================
=                 Starting SAMBA, logs after this are from SAMBA                  =
===================================================================================
smbd version 4.12.5-Debian started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
INFO: Profiling support unavailable in this build.
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections

```

**Comment by TimJDFletcher** [comment]
Could you test it without mergefs and just using ext4 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thewinger** [comment]
I'm afraid I can't.
I'm not sure if that would mess my server setup and I have many files there.

**Comment by TimJDFletcher** [comment]
You could test if mergefs is the problem by using /tmp for the backups.

I think that the problem is how macOS, SAMBA and mergefs ACLs interact, but this is a guess only.

**Comment by thewinger** [comment]
I have tried with another container https://github.com/mbentley/docker-timemachine and it works pointing at the same folder within the mergerfs

**Comment by TimJDFletcher** [comment]
Excellent that’s good news 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
